apiVersion: v1
kind: PersistentVolume
metadata:
        name: pv-sts-5
        labels: 
                purpose: sts-test
spec:
        capacity:
                storage: 5Gi
        volumeMode: Filesystem
        accessModes:
                - ReadWriteOnce
        storageClassName: manual
        hostPath:
                path: "/root/pv5"

