apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
        name: secret-viewer
subjects:
- kind: User
  name: manager
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secret-viewer
  apiGroup: ""

