apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        name: deployment-manager-role-binding
        namespace: dev
subjects:
- kind: User
  name: manager
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""

