apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
        namespace: dev
        name: deployment-manager
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "pods", "replicasets"]
  verbs: ["get", "list","watch","create","update"]

