apiVersion: v1
kind: Service
metadata:
        name: service-api
        labels:
                app: service
spec:
        selector:
                app: api
        ports:
        - protocol: TCP
          port: 81 #service port
          targetPort: 80 #container port

